"""tambah filelocation

Revision ID: 0a2833870b41
Revises: e434da6b09c4
Create Date: 2024-04-02 23:28:28.852080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2833870b41'
down_revision = 'e434da6b09c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bpom_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'file_locations', ['file_location_id'], ['id'])

    with op.batch_alter_table('halal_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'file_locations', ['file_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('halal_certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_location_id')

    with op.batch_alter_table('bpom_certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_location_id')

    # ### end Alembic commands ###
