"""add new column file locations

Revision ID: 404e96ebbdbb
Revises: 8a0022b6da5a
Create Date: 2024-04-03 07:54:33.232363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404e96ebbdbb'
down_revision = '8a0022b6da5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metaname', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_locations', schema=None) as batch_op:
        batch_op.drop_column('filename')
        batch_op.drop_column('metaname')

    # ### end Alembic commands ###
