"""tambah jenis

Revision ID: b9b31ab2ed4a
Revises: 0a2833870b41
Create Date: 2024-04-02 23:36:14.559845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b31ab2ed4a'
down_revision = '0a2833870b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_locations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
